version: '3'

services:
  test:
    image: bash:5.0.2
    volumes:
      - env-inject:/test/
    command: sh -c "find /test -type f -print0 | xargs -0 cat"
    depends_on:
      - env-injector

  env-injector:
    build:
      context: .
    image: emnify/env-injector:latest
    volumes:
      - ./test/:/test/
      - env-inject:/injected/
      - ./envInject.sh:/init.sh
    command:
     - /test/
     - /injected/
    environment:
      - HELLO_WORLD=1337
      - FOO_BAR=this is a value = @

volumes:
  env-inject:

